from pyspark.sql.types import (
    StructType,
    StructField,
    IntegerType,
    DoubleType,
    StringType,
)

csv_schema = StructType(
    [
        StructField("id", IntegerType(), False),
        StructField("loan_amnt", DoubleType(), True),
        StructField("funded_amnt", DoubleType(), True),
        StructField("funded_amnt_inv", DoubleType(), True),
        StructField("term", StringType(), True),
        StructField("int_rate", StringType(), True),
        StructField("installment", DoubleType(), True),
        StructField("grade", StringType(), True),
        StructField("sub_grade", StringType(), True),
        StructField("emp_length", StringType(), True),
        StructField("home_ownership", StringType(), True),
        StructField("annual_inc", DoubleType(), True),
        StructField("verification_status", StringType(), True),
        StructField("issue_d", StringType(), True),
        StructField("loan_status", StringType(), True),
        StructField("desc", StringType(), True),
        StructField("purpose", StringType(), True),
        StructField("title", StringType(), True),
        StructField("zip_code", StringType(), True),
        StructField("addr_state", StringType(), True),
        StructField("dti", DoubleType(), True),
        StructField("delinq_2yrs", IntegerType(), True),
        StructField("earliest_cr_line", StringType(), True),
        StructField("fico_range_low", IntegerType(), True),
        StructField("fico_range_high", IntegerType(), True),
        StructField("inq_last_6mths", IntegerType(), True),
        StructField("mths_since_last_delinq", IntegerType(), True),
        StructField("mths_since_last_record", IntegerType(), True),
        StructField("open_acc", IntegerType(), True),
        StructField("pub_rec", IntegerType(), True),
        StructField("revol_bal", DoubleType(), True),
        StructField("revol_util", StringType(), True),
        StructField("total_acc", IntegerType(), True),
        StructField("initial_list_status", StringType(), True),
        StructField("out_prncp", IntegerType(), True),
        StructField("out_prncp_inv", IntegerType(), True),
        StructField("total_pymnt", DoubleType(), True),
        StructField("total_pymnt_inv", DoubleType(), True),
        StructField("total_rec_prncp", DoubleType(), True),
        StructField("total_rec_int", DoubleType(), True),
        StructField("total_rec_late_fee", DoubleType(), True),
        StructField("recoveries", DoubleType(), True),
        StructField("collection_recovery_fee", DoubleType(), True),
        StructField("last_pymnt_d", StringType(), True),
        StructField("last_pymnt_amnt", DoubleType(), True),
        StructField("next_pymnt_d", StringType(), True),
        StructField("last_credit_pull_d", StringType(), True),
        StructField("last_fico_range_high", IntegerType(), True),
        StructField("last_fico_range_low", IntegerType(), True),
        StructField("collections_12_mths_ex_med", IntegerType(), True),
        StructField("mths_since_last_major_derog", IntegerType(), True),
        StructField("policy_code", IntegerType(), True),
        StructField("application_type", StringType(), True),
    ]
)

amount_cols = [
    "loan_amnt",
    "funded_amnt",
    "funded_amnt_inv",
    "revol_bal",
    "total_pymnt",
    "total_pymnt_inv",
    "total_rec_prncp",
    "total_rec_int",
    "recoveries",
    "collection_recovery_fee",
    "last_pymnt_amnt",
]
